name: vasx_ui
description: >
  vasX UI — a collection of beautiful, reusable Flutter widgets including
  smart dropdowns, date pickers, multi-step wizards, animated popup menus,
  and responsive data tables. Built for production-grade Flutter apps.
<<<<<<< HEAD
<<<<<<< Updated upstream
version: 0.0.2
=======
version: 2.0.0
>>>>>>> c679b0932f155dc101d9596542e3b5989bc6e5c1
homepage: https://github.com/Sabari-Vasan-SM/vasX-UI.git
=======
version: 2.0.0
homepage: https://github.com/Sabari-Vasan-SM/vasX-UI
repository: https://github.com/Sabari-Vasan-SM/vasX-UI
issue_tracker: https://github.com/Sabari-Vasan-SM/vasX-UI/issues
>>>>>>> Stashed changes

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
